---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-keyvault-sync-controller
  namespace: kube-system
  labels:
    app: azure-keyvault-sync-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-keyvault-sync-controller
  template:
    metadata:
      labels:
        app: azure-keyvault-sync-controller
    spec:
      serviceAccountName: azure-keyvault-sync-controller
      containers:
        - name: controller
          image: <registry>/azure-keyvault-sync-controller:latest  # TBD
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL
